.flake8
.github/workflows/lint.yml
.github/workflows/main.yml
README.ENG.md
README.md

Lint Python Code

---

lazyllm/common/logger.py

fix: do not need to register for windows(spawn)

fix: do not need to register for windows(spawn)

---

lazyllm/docs/components.py
lazyllm/docs/flow.py
lazyllm/docs/module.py
lazyllm/docs/tools.py
lazyllm/docs/utils.py

- 添加了提取文档中的examples功能
- 修正了文档中的例子

exports all examples

---

lazyllm/components/utils/downloader/model_downloader.py
lazyllm/module/module.py
lazyllm/tools/rag/docment.py

- Add new environment variable: `LAZYLLM_DATA_PATH`
- TrainableModule supported auto model path,
- Document in RAG supported auto file path

Add auto path for data and model

---

lazyllm/common/logger.py

 Fixed the bug caused by the given path not existing in the logging system.

---

.github/workflows/main.yml
lazyllm/launcher.py
tests/advanced_tests/test_deploy.py
tests/basic_tests/test_module.py

- Adapt to SCC downgrade to 2.5.2, by changing workspace-name to workspace-id
- Pytest performs cleanup for failed tasks

Fixed CI stability

---

lazyllm/configs.py
lazyllm/launcher.py

feature: support keep record for sensecore to see logs in the website

feature: support keep record for sensecore

---

lazyllm/launcher.py
lazyllm/module/module.py

Solve the problem of CI service not being killed by increasing the frequency of job_id capture.

Fixed a bug that caused the test to get stuck due to resources on sco not being released.

---

lazyllm/common/logger.py
lazyllm/tools/webpages/webmodule.py

Fixes https://github.com/LazyAGI/LazyLLM/issues/59

add log_once for logger system

---

lazyllm/tools/rag/parser.py

LOG friendly error for the user

feature: Report Error in Bad Internet Conditions

---

.github/workflows/main.yml

add pull_request_target

---

.github/workflows/main.yml

This reverts commit 2e0d357e6c6e4ea8cbd1f945cf4e9965a9d00acc.

Revert "add pull_request_target (#71)"

---

lazyllm/tools/rag/data_loaders.py
lazyllm/tools/rag/doc_impl.py
lazyllm/tools/rag/index.py
lazyllm/tools/rag/parser.py
lazyllm/tools/rag/store.py
lazyllm/tools/rag/transform.py
tests/basic_tests/test_doc_impl.py
tests/basic_tests/test_doc_node.py
tests/basic_tests/test_sentence_splitter.py

- dynamic parser
- default index
- update node data structure

add transform and similarity for doc-V2

---

lazyllm/tools/webpages/webmodule.py

feature: log-error-for-webmodule

---

README.CN.md
README.md
lazyllm/components/auto/autodeploy.py
lazyllm/components/stable_diffusion/stable_diffusion3.py
lazyllm/components/utils/downloader/model_mapping.py
lazyllm/tools/webpages/webmodule.py
requirements.full.txt
tests/advanced_tests/test_deploy.py

1. Add Stable Diffusion3 to LazyLLM and give demo
2. Fixed the issue where webmodule input was eaten during the first chat.
demo:

Add stable diffusion3 to lazyllm and give demo

---

lazyllm/common/logger.py
lazyllm/components/deploy/base.py
tests/legacy/parallel_launch.py

- reduce fix pickle
- remove long dummy

fix a bug which cause TrainableModule got stuck when using lazyllm.LOG

---

README.CN.md
README.md
lazyllm/components/deploy/relay/server.py
lazyllm/module/module.py
lazyllm/tools/webpages/webmodule.py
tests/basic_tests/test_module.py

1. lost prompt；
2. async of loop.run_in_executor not support kargs；
3. ` image` ref before assign

Fixed bug: lost prompt, loop.run_in_executor not support kargs

---

lazyllm/tools/webpages/webmodule.py

feature: handle-keyboard-interrupt and exit elegantly

feature: handle-keyboard-interrupt

---

.github/workflows/main.yml
README.CN.md
README.md
examples/chatbot.py
examples/chatbot_online.py
examples/painting.py
examples/rag.py
examples/rag_online.py
examples/story.py
examples/story_online.py
lazyllm/__init__.py
lazyllm/docs/module.py
lazyllm/module/__init__.py
lazyllm/module/automodel.py
lazyllm/module/module.py
lazyllm/module/onlineChatModule/onlineChatModule.py
lazyllm/module/onlineChatModule/onlineChatModuleBase.py
lazyllm/module/onlineChatModule/qwenModule.py
lazyllm/module/onlineEmbedding/onlineEmbeddingModule.py
lazyllm/tools/rag/component/sent_embed.py
lazyllm/tools/webpages/webmodule.py
tests/advanced_tests/test_example.py
tests/basic_tests/test_module.py
tests/charge_tests/test_example.py

- Give 4 Demos, their tests and readme:
- chatbot  (online and offline)
- rag (online and offline)
- painting (only offline)
- story (online and offline)
- Add formatter for urlmodule
- Add AutoModel
- Some bugs fixed:
- `OnlineEmbeddingModule` support no source;
- OnlineEmbeding not support list of str;
- `OnlineChatModuleBase` no trained for deploy return None

Give 4 Demos and add formatter for urlmodule

---

tests/charge_tests/test_onlineChat_fc.py

Fix FC unit tests parameters incorrect problem

---

lazyllm/components/deploy/__init__.py
lazyllm/components/deploy/lmdeploy.py
lazyllm/components/utils/downloader/model_mapping.py
lazyllm/docs/components.py
lazyllm/module/module.py
lazyllm/tools/webpages/webmodule.py
tests/advanced_tests/test_deploy.py
tests/advanced_tests/test_example.py

- Support MultiModal :
- llava-1.5-7b, llava-1.5-13b
- internvl-chat-2b-v1-5, internvl-chat-v1-5
- Support LMDeploy

Support MultiModal and LMDeploy

---

lazyllm/components/prompter/builtinPrompt.py
lazyllm/module/onlineChatModule/onlineChatModuleBase.py
lazyllm/tools/__init__.py
lazyllm/tools/classifier/__init__.py
lazyllm/tools/classifier/intent_classifier.py
lazyllm/tools/rag/base.py
lazyllm/tools/webpages/webmodule.py

1. WeModule has a bug when dealing global history which causes only the last module can use llm_history
2. There's a bug when bind argument to rag inside some pipeline, which will cause a string argument becomes a lazyllm.package with only one string

Add intent detection module and fix some bug.

---

lazyllm/tools/rag/rerank.py
tests/basic_tests/test_reranker.py

add reranker

---

lazyllm/configs.py
tests/advanced_tests/full_test/test_deploy.py
tests/basic_tests/test_config.py

- Clear the environment variables before test_AutoModel and restore them after the test.
- Add refresh for config
- Add a test case for it
- Remove the redundant: redis_url

Clear EV before test_AutoModel and restore them after test

---

lazyllm/docs/tools.py

create db file in sql example

---

lazyllm/launcher.py

Background: Preparing for SCO: Replace A100 with A800. 
- Add a new environment variable: `LAZYLLM_SCO_RESOURCE_TYPE`

Add new EnvVar: LAZYLLM_SCO_RESOURCE_TYPE

---

lazyllm/components/utils/downloader/model_downloader.py

Safely creates a symbolic link by removing any existing link

Safely creates a symbolic link by removing any existing link

---

lazyllm/docs/tools.py

Remove individual example for SQLiteTool's method, leave only one example that covers all method.

remove individual example for SQLiteTool's method

---

lazyllm/docs/tools.py

As the title. Add missing import module

fix doc problem in IntentClassifier example

---

lazyllm/cli/deploy.py
lazyllm/cli/install.py
lazyllm/cli/main.py
lazyllm/cli/run.py
lazyllm/launcher.py
lazyllm/module/module.py
lazyllm/module/onlineChatModule/onlineChatModuleBase.py
lazyllm/tools/agent/functionCall.py
lazyllm/tools/agent/planAndSolveAgent.py
lazyllm/tools/agent/rewooAgent.py
lazyllm/tools/agent/toolsManager.py
pyproject.toml

- lazyllm deploy internlm2-chat-7b
- lazyllm deploy internlm2-chat-7b --framework=vllm
- lazyllm deploy internlm2-chat-7b --chat=True
- lazyllm deploy internlm2-chat-7b --chat=True --framework=lightllm

add `lazyllm deploy modelname` cli

---

lazyllm/tools/classifier/intent_classifier.py
tests/advanced_tests/full_test/test_example.py

fix vllm bug

---

lazyllm/tools/webpages/webmodule.py

Fork on MacOS has lots of bugs, remove subprocess to solve it

fix webmodule bug together with loguro on MacOS

---

lazyllm/cli/deploy.py
lazyllm/cli/install.py
lazyllm/cli/main.py
lazyllm/cli/run.py
lazyllm/module/automodel.py
tests/advanced_tests/full_test/test_deploy.py

1. `lazyllm run chatbot [--model MODEL] [--source {openai,sensenova,glm,kimi,qwen,doubao}] [--framework {lightllm,vllm,lmdeploy}]`
2. `lazyllm run rag [--model MODEL] [--source {openai,sensenova,glm,kimi,qwen,doubao}] [--framework {lightllm,vllm,lmdeploy}] --documents DOCUMENTS`

add lazyllm run cli

---

lazyllm/launcher.py

Change default sco resource

---

lazyllm/components/auto/auto_helper.py
lazyllm/components/auto/dependencies/requirements.py

Support the inspection of packages with the prefix “lazyllm-” under the Auto.

Support the inspection of packages with the prefix “lazyllm-” under the Auto

---

lazyllm/docs/module.py
lazyllm/module/module.py

Support ServerModule port

---

README.md
docs/en/Cookbook/multimodal_robot.md
lazyllm/components/prompter/prompter.py
lazyllm/components/text_to_speech/__init__.py
lazyllm/engine/engine.py
lazyllm/engine/node.py
lazyllm/module/module.py
tests/advanced_tests/standard_test/test_engine.py

add engine multimedia tests

---

lazyllm/components/auto/autodeploy.py
lazyllm/components/embedding/embed.py
tests/advanced_tests/standard_test/test_deploy.py

Replace Embedding of LlamaIndex by the transformers。

Replace Embedding of LlamaIndex by the transformers

---

lazyllm/docs/tools.py
tests/charge_tests/test_sql_tool.py
tests/charge_tests/utils.py

1. Drop obsolete tables created by unit test. (Which is created by interrupted ci test)
2. Add doc

Add drop obsolete table in unittest. Add doc for SqlManager

---

lazyllm/components/auto/autodeploy.py
tests/advanced_tests/standard_test/test_deploy.py

Auto select lmdeploy for vllm models.

Auto select lmdeploy for vllm models.

---

lazyllm/components/stable_diffusion/stable_diffusion3.py
lazyllm/components/text_to_speech/bark.py
lazyllm/components/text_to_speech/chattts.py
lazyllm/components/text_to_speech/musicgen.py
lazyllm/docs/components.py
lazyllm/tools/webpages/webmodule.py
tests/advanced_tests/full_test/test_deploy.py
tests/advanced_tests/full_test/test_example.py
tests/advanced_tests/standard_test/test_deploy.py

Unified Name for return audio and images

Unified Name for return audio and images

---

lazyllm/launcher.py

Bug Fixed: pop stop processes.

Bug Fixed: pop stop processes.

---

lazyllm/engine/engine.py
lazyllm/engine/node.py
tests/basic_tests/test_engine.py
tests/charge_tests/test_sql_tool.py

1. set id_map(backend id to frontend id).
2. change make_code args in test

fix bug: map backend_nodeid to  frontend_nodeid

---

lazyllm/tools/rag/doc_manager.py

fix doc manager/add files  metadata format

---

lazyllm/common/common.py
lazyllm/components/utils/downloader/model_downloader.py
lazyllm/engine/lightengine.py
lazyllm/module/__init__.py
lazyllm/module/module.py

1. Supported re-download models if they are corrupted.
2. Fixed a bug where incomplete download files were not cleared on failure，because of the mismatch between the deletion path and the download path.
3. Fixed an issue where during the download process, the user’s interruption by pressing Ctrl+C could not be captured due to improper exception handling, resulting in the inability to clear the downloaded files.
Known Issues:
Re-downloading of incomplete files is not supported in the current ModelScope version. A fix is pending release (see issue: https://github.com/modelscope/modelscope/issues/1114)

Enhance Model Download Reliability and Error Handling

---

lazyllm/components/utils/downloader/model_mapping.py

Add new Models:
- sensechat
- yi-vl-6b
- Codestral
SenseChat：
Codestral：
Yi-VL-6B：

Add yi-vl-6b, sensechat and Codestral

---

lazyllm/engine/lightengine.py
lazyllm/module/onlineChatModule/sensenovaModule.py
lazyllm/tools/train_service/client.py

Support sensenova api validate.

Support SenseNova API validate.

---

lazyllm/components/finetune/llamafactory.py
lazyllm/module/module.py

Fixed internlm2_5, llama-2, llama-3 cannot get llamafactory-template

Fixed internlm2_5, llama-2, llama-3 cannot get llamafactory-template

---

lazyllm/components/utils/downloader/model_downloader.py

Simple suppoted validate model_path for local model

Simple suppoted validate model_path for local model

---

tests/advanced_tests/standard_test/test_engine.py

Add test-case for Infer-Service: VQA and ChatTTS

Add test-case for Infer-Service: VQA and ChatTTS

---

lazyllm/docs/tools.py
lazyllm/tools/tools/__init__.py
lazyllm/tools/tools/tencent_search.py

Supported Tencent Search

---

examples/distill_deepseek_r1.py

Add Argparse for Distill DeepSeek-R1

---

lazyllm/tools/rag/document.py
lazyllm/tools/sql/sql_manager.py
tests/charge_tests/test_sql_tool.py

1. Decline create/drop table
2. Use original session without commit to prevent insert/delete operation

Update SqlManager checking logic

---

examples/rag_milvus_store.py
lazyllm/docs/tools.py

1. Mistyping in tools doc
2. Remove shuit in `__del__` to prevent it from pickle error.

Fix examle running problems.

---

lazyllm/tools/rag/similarity.py

…her information of the decorated function

Modify register_similarity to retain information of function

---

lazyllm/common/__init__.py
lazyllm/common/utils.py
lazyllm/tools/tools/http_tool.py
tests/advanced_tests/standard_test/test_http_tool.py

This reverts commit 335b4c04322bff67b258230055c3b6790c71dd2c.

Revert "Fix HttpTool compile bug (#466)"

---

lazyllm/docs/module.py

add instrusction of TrainableModule(Chinese Version)

---

lazyllm/module/onlineChatModule/onlineChatModuleBase.py
lazyllm/module/onlineChatModule/sensenovaModule.py
lazyllm/tools/webpages/webmodule.py

1. Supported DeepSeek reasoning content:
2. Fixed bug double response in gradio,https://github.com/LazyAGI/LazyLLM/issues/478:

Supported DeepSeek reasoning content and fixed bug double response in gradio

---

lazyllm/module/onlineChatModule/doubaoModule.py
lazyllm/module/onlineChatModule/glmModule.py
lazyllm/module/onlineChatModule/qwenModule.py

Adjust the priority of model name configurations in the doubao, qwen, and glm modules.

Fix Model Name

---

lazyllm/components/deploy/infinity.py

This PR adds GPU allocation logic when using the EmptyLauncher to:
- Check for available GPUs when ngpus is specified
- Allocate the required number of GPUs if available
- Add the --device-id parameter to the infinity_emb command with the allocated GPU IDs
- Raise a clear error message when insufficient GPUs are available
The changes ensure proper GPU resource management when launching infinity_emb with a specified number of GPUs through the EmptyLauncher.
1. Using:
```python
embed = lazyllm.TrainableModule('bge-m3').deploy_method(deploy.Infinity, launcher=launchers.empty(ngpus=2))
```
2. Generated CMD:
3. GPU Status:

Add GPU allocation logic for EmptyLauncher in infinity_emb command generation

---

lazyllm/cli/deploy.py
lazyllm/components/utils/downloader/model_mapping.py
requirements.full.txt

1.resolve version conflicts, pin optimum version to 1.16.2
2.add new model mappings for bge-reranker-v2-m3 bge-vl-v1.5-mmeb qwen2.5-vl-32b-instruct
3.add deployment parameter for deploy cli

new model mappings for bge-reranker-v2-m3 bge-vl-v1.5-mmeb qwen2.5-vl-32b-instruct

---

lazyllm/components/finetune/llama_factory/lora_export.yaml

Fixed an issue when merging and exporting weights.

---

tests/doc_check/test_doc_api_check.py

添加功能：
1. 文档不能直接写在函数里面，要以add_doc的方式加中英双语
2. 确保每个函数的文档都是google风格，且保证Args和注解一致（Dict，dict视为一致）

fix: improve doc_api_check test logic

---

lazyllm/components/deploy/embed.py

CodeFix：RerankDeploy BGEVLEmbedding to private

CodeFix：RerankDeploy BGEVLEmbedding to private

---

docs/en/API Reference/components.md
docs/en/API Reference/module.md
docs/en/API Reference/tools.md
docs/zh/API Reference/components.md
docs/zh/API Reference/module.md
docs/zh/API Reference/tools.md
lazyllm/docs/components.py
lazyllm/docs/tools.py

DOC-W1：fix bug Dev/doc week1

---

lazyllm/tools/rag/doc_impl.py
lazyllm/tools/rag/doc_processor.py
lazyllm/tools/rag/document.py

add description field for Document and algo/list api for DocumentProcessor

add algorithm description for Document and algo list api

---

docs/en/API Reference/common.md
docs/en/API Reference/components.md
docs/en/API Reference/module.md
docs/en/API Reference/tools.md
docs/zh/API Reference/common.md
docs/zh/API Reference/components.md
docs/zh/API Reference/module.md
docs/zh/API Reference/tools.md
lazyllm/docs/common.py
lazyllm/docs/components.py
lazyllm/docs/module.py
lazyllm/docs/tools.py

DOC-W2:ver2-clean

---

lazyllm/docs/tools.py

DOCW2:fix indexbase

---

docs/en/API Reference/common.md
docs/en/API Reference/components.md
docs/en/API Reference/flow.md
docs/en/API Reference/launcher.md
docs/en/API Reference/module.md
docs/en/API Reference/tools.md
docs/mkdocs.template.yml
docs/zh/API Reference/common.md
docs/zh/API Reference/components.md
docs/zh/API Reference/flow.md
docs/zh/API Reference/launcher.md
docs/zh/API Reference/module.md
docs/zh/API Reference/tools.md
lazyllm/docs/common.py
lazyllm/docs/components.py
lazyllm/docs/flow.py
lazyllm/docs/launcher.py
lazyllm/docs/module.py
lazyllm/docs/tools.py

Week3 merge main

---

docs/en/API Reference/common.md
docs/en/API Reference/components.md
docs/en/API Reference/configs.md
docs/en/API Reference/flow.md
docs/en/API Reference/launcher.md
docs/en/API Reference/module.md
docs/en/API Reference/tools.md
docs/mkdocs.template.yml
docs/zh/API Reference/common.md
docs/zh/API Reference/components.md
docs/zh/API Reference/configs.md
docs/zh/API Reference/flow.md
docs/zh/API Reference/launcher.md
docs/zh/API Reference/module.md
docs/zh/API Reference/tools.md
lazyllm/common/__init__.py
lazyllm/docs/common.py
lazyllm/docs/components.py
lazyllm/docs/configs.py
lazyllm/docs/flow.py
lazyllm/docs/launcher.py
lazyllm/docs/module.py
lazyllm/docs/tools.py

add api docs for lazyllm functions and class (week3) [skip ci]

---

docs/en/API Reference/components.md
docs/zh/API Reference/components.md
lazyllm/docs/components.py
lazyllm/docs/module.py
lazyllm/docs/tools.py

Doc W4：add

---

docs/en/API Reference/components.md
docs/en/API Reference/module.md
docs/en/API Reference/tools.md
docs/zh/API Reference/components.md
docs/zh/API Reference/module.md
docs/zh/API Reference/tools.md
lazyllm/docs/components.py
lazyllm/docs/module.py
lazyllm/docs/tools.py

- Merge: https://github.com/LazyAGI/LazyLLM/pull/680
- Fixed All Bugs

Merge PR#680 and fixed all bugs

---

lazyllm/tools/rag/store/segment/opensearch_store.py
lazyllm/tools/rag/store/vector/milvus_store.py

Fix Bugs for milvus store when using doc processor and upload huge amount of files. Use queue and ClientPool to fix it.
Additionally, modify `OpenSearchStore` to improve its performance in high concurrency scenario.
Closes #713 
---
- User-visible changes
- Configuration change instructions
- Migration steps
- Known issues

[Bugfix]: fix error for milvus standalone and OpenSearch in high concurrency scenario

---

lazyllm/module/llms/onlinemodule/supplier/sensenova.py

Correct the sensenova api_key validation URL

---

docs/en/Best Practice/LocalModel.md
docs/en/Best Practice/rag.md
docs/nav_en.yml
docs/nav_zh.yml
docs/zh/Best Practice/LocalModel.md
docs/zh/Best Practice/rag.md

- 为TrainableModule撰写最佳实践
- Fix #179
1. 无需测试
```
无

add bestpractice for trainablemodule

---

docs/en/API Reference/common.md
docs/en/API Reference/components.md
docs/en/API Reference/launcher.md
docs/en/API Reference/module.md
docs/en/API Reference/tools.md
docs/zh/API Reference/common.md
docs/zh/API Reference/components.md
docs/zh/API Reference/launcher.md
docs/zh/API Reference/module.md
docs/zh/API Reference/tools.md
lazyllm/docs/common.py
lazyllm/docs/components.py
lazyllm/docs/flow.py
lazyllm/docs/hook.py
lazyllm/docs/launcher.py
lazyllm/docs/module.py
lazyllm/docs/tools.py

Prefix dict has been built successfully.

DOC-W5： add docstring for mainly common,module,components,launcher,flow,tools

---

.github/workflows/lint.yml
Makefile

- lint中增加flake8-bugbear和flake8-quotes，提供更强的检查，重点是要求单引号优先和不能在函数签名中使用可修改的变量作为默认值
- 修改lint检查机制，只查询用户本次提交的pr中修改到的文件，不查询其他未涉及的文件
- 
1. 无需测试
2. 
3. 
- 
```bash
$ make lint-only-diff
🔍 Collecting changed Python files...
✅ No Python file changes to lint.
✅ Lint passed: no print(...) statements found.
```

add stronger lint for modified files

---

lazyllm/docs/common.py
lazyllm/docs/components.py
lazyllm/docs/module.py
lazyllm/docs/tools.py

- 
- 修改api文档渲染问题
1. 
2. 
3. 
- 
```python
```

fix api documents

---

lazyllm/launcher.py

- 修复launcher的lint
- 
1. 无需测试
2. 
3. 
-

fix launcher lint

---

lazyllm/common/__init__.py
lazyllm/common/common.py
lazyllm/common/globals.py
lazyllm/components/deploy/base.py
lazyllm/components/deploy/relay/base.py
lazyllm/components/deploy/relay/server.py
lazyllm/components/deploy/vllm.py
lazyllm/module/servermodule.py
tests/charge_tests/test_online_embedding.py

- 给ServerModule增加ray的启动方式，以支持分布式部署
- 
1. 单元测试
2. 
3. 
- 
```python
```

add ray for servermodule

---

.flake8
.github/workflows/lint.yml
.github/workflows/main.yml
docs/ipynb2md.py
docs/link_assets.py
lazyllm/components/deploy/__init__.py
lazyllm/components/formatter/formatterbase.py
lazyllm/docs/utils.py
lazyllm/thirdparty/__init__.py
lazyllm/thirdparty/modules.py
lazyllm/tools/__init__.py
lazyllm/tools/eval/rag_retriever_metrics.py
lazyllm/tools/infer_service/serve.py
lazyllm/tools/services/services.py
lazyllm/tools/train_service/serve.py
scripts/flake8_no_direct_imports.py

- 增加对thirdparty的检查，thirdparty中出现的包名，不能直接import（除用于测试的os以外）
- 
1. 无需测试
2. 
3. 
- 
```python
```
make lint

add thirdparty test for flake8
