LazyAGI/LazyLLM

lazyllm/tools/webpages/webmodule.py

Case when handling string without json type
"/home/mnt/yewentao/LazyLLM/lazyllm/tools/webpages/webmodule.py", line 222, in _respond_stream
result, log = get_log_and_message(result)
File "/home/mnt/yewentao/LazyLLM/lazyllm/tools/webpages/webmodule.py", line 205, in get_log_and_message
if "type" not in r["choices"][0] or (
TypeError: list indices must be integers or slices, not str

fix: web module unexpected type error

---

lazyllm/common/logger.py

including call_once, the stack depth = 2

fix: log once stack depth

---

lazyllm/tools/rag/data_loaders.py
lazyllm/tools/rag/doc_impl.py
lazyllm/tools/rag/index.py
lazyllm/tools/rag/store.py
lazyllm/tools/rag/transform.py
tests/basic_tests/test_doc_node.py
tests/basic_tests/test_store.py

- chromadb support
- only roots have metadata

add chromadb store

---

lazyllm/common/globals.py
lazyllm/components/auto/autodeploy.py
lazyllm/components/text_to_speech/bark.py
lazyllm/components/utils/downloader/model_mapping.py
lazyllm/tools/webpages/webmodule.py
tests/advanced_tests/test_deploy.py

- sepport TTS model: [bark](https://huggingface.co/docs/transformers/v4.43.3/en/model_doc/bark)

Support bark for TTS

---

lazyllm/components/deploy/lmdeploy.py
lazyllm/components/deploy/lmdeploy/chat_template.json
lazyllm/components/utils/downloader/model_downloader.py
lazyllm/components/utils/downloader/model_mapping.py
tests/advanced_tests/full_test/test_deploy.py

Background: `internlm2_5-7b-chat` not in model_name_mapping , only LMDeploy can run. vLLM and LightLLm cannot get `prompt_keys`.
- Remove mapping redundancy, 
- LMDeploy supports empty chat templates
- let model(LLM) which not in model_mapping can get prompt_keys

Add model into model_name_mapping 

---

lazyllm/launcher.py

Due to the absence of “wait” in EmptyLauncher, the deployment starts immediately after the training is initiated.

EmptyLauncher lack wait

---

README.CN.md
README.md
lazyllm/components/utils/downloader/model_downloader.py
lazyllm/components/utils/downloader/model_mapping.py

- Modify the missing VQA model name in the readme
- Add a print error for the unset token for the mode needed applying.
- Add a new VQA provider to model_mapping.

Mdify missing vqa name in readme

---

lazyllm/cli/install.py

修复lazyllm install full/standard的时候，读toml下的tool.poetry.extras，但是没有去查询tool.poetry.dependencies中的版本

fix install bug

---

lazyllm/common/common.py
tests/basic_tests/test_flow.py

Please use following code for test
```
import lazyllm
from lazyllm import pipeline, bind
import cloudpickle
with pipeline() as ppl:
ppl.f1 = lambda x: str(len(x))
ppl.formatter = (lambda length, query: dict(length=length, query=query)) | bind(query=ppl.input)
ppl.f2 = lambda y: f"The original query is : {y['query']}, length is : {y['length']}"
am = lazyllm.ActionModule(ppl)
pkl_am = cloudpickle.dumps(am)
new_am = cloudpickle.loads(pkl_am)
print(new_am("Hello World"))
sm = lazyllm.ServerModule(ppl)
sm.start()
print(sm("Hello World"))
```

fix bind pickle bug

---

lazyllm/components/utils/downloader/model_downloader.py
lazyllm/configs.py

Fixed bug: 
1. Unexpected environment variables starting with `LAZYLLM_` will cause an error during refresh; 
3. Optimization of Downloader error reporting.

config.refresh under lazyllm- no in dict, and download error2warning

---

lazyllm/components/finetune/alpacalora.py
lazyllm/components/finetune/collie.py
lazyllm/components/finetune/llamafactory.py
lazyllm/docs/components.py
lazyllm/module/module.py
tests/advanced_tests/standard_test/test_finetune.py

For models that are only deployed, lazy deployment is used on a single machine, and there is a merge folder in the current path, merge will be used first. This will cause errors in model loading.
【Bug】
Reproduction conditions:
- Single machine
- There is a `merge` folder in the current path
- Only deploy models
【Solve】

Solved the bug of inference failure when target_path is set but there is no model in it

---

lazyllm/launcher.py
pyproject.toml
requirements.full.txt
requirements.txt

**Background** 
Using LightLLM to call the process kill in the code can only kill the parent process, and the child process cannot be killed, which will become a zombie process. This issue does not occur in vLLM. 
**Solution**
Recursively traverse all child processes of the parent process to actively kill them.
**Problem**
**Solved**

Add kill subprocess for EmptyLauncher

---

lazyllm/launcher.py

EmptyLauncher supports setting `CUDA_VISIBLE_DEVICES` based on the remaining GPU memory for each GPU.

EmptyLauncher supported cuda_visible_devices by memory left order

---

lazyllm/module/module.py
lazyllm/tools/sql/sql_tool.py
tests/charge_tests/test_sql_tool.py
tests/charge_tests/utils.py

Support local llm model token usage and add escape for database password

---

lazyllm/docs/components.py
lazyllm/launcher.py
lazyllm/module/onlineChatModule/openaiModule.py
lazyllm/tools/train_service/client.py

1. Avoid unnecessary task termination post-completion.
2. Ensure consistency between documentation and code in multimodal modules.
3. Supported SFT for openai
Three tasks were fine-tuned：
- The first task failed, 
- The second task succeeded, 
- The third task was cancelled midway. 
This verified all fine-tuned APIs:
- `online_model_train`
- `online_model_get_all_trained_models`
- `online_model_cancel_training`
- `online_model_get_training_status`
- `online_model_get_training_log`
- `online_model_get_training_cost`
Log of a successful task:

 Supported SFT for OpenAI, Optimize Task Termination and Align Docs with Code in Multimodal Modules

---

lazyllm/components/finetune/llamafactory/sft.yaml
lazyllm/tools/train_service/client.py

This PR addresses the issue of the incorrect usage of `batch_size_per_device` and `batch_size`. In the transformers code, the total_train_batch_size is calculated as **total_train_batch_size = _train_batch_size * gradient_accumulation_steps * world_size**.
Here, `_train_batch_size` corresponds to `batch_size_per_device` in Llamafactory, which is similar to a `micro_batch_size`.
Code in Transformers:
Log in Llamafactory and Code in Transformers:
To resolve this, in LazyLLM, I have fixed `gradient_accumulation_steps` to 1. Given a `batch_size`, the correct calculation for `batch_size_per_device` should be `batch_size_per_device // n_gpus`. This ensures that the batch size is properly distributed across the available GPUs.
- 2 GPUs OOM:
- 4 GPUs OK:

Fixed batch_size_per_device and batch_size misuse in LazyLLM

---

lazyllm/components/auto/autodeploy.py
lazyllm/components/auto/autofinetune.py
lazyllm/components/embedding/embed.py
lazyllm/components/speech_to_text/sense_voice.py
lazyllm/components/stable_diffusion/stable_diffusion3.py
lazyllm/components/text_to_speech/bark.py
lazyllm/components/text_to_speech/chattts.py
lazyllm/components/text_to_speech/musicgen.py
lazyllm/components/utils/downloader/model_downloader.py
lazyllm/module/module.py
lazyllm/tools/train_service/serve.py

- Capture download progress based on file size. Previous solution based on `tqdm` is abolished: https://github.com/LazyAGI/LazyLLM/pull/390
- Add new interface for verification:
- `validate_token`
- `validate_model_id`

Unified Download Progress for Huggingface and Modelscope

---

lazyllm/tools/rag/milvus_store.py

enable milvus pagination query

---

lazyllm/components/deploy/infinity.py
lazyllm/components/embedding/embed.py
lazyllm/module/onlineEmbedding/glmEmbed.py
lazyllm/module/onlineEmbedding/onlineEmbeddingModule.py
lazyllm/module/onlineEmbedding/qwenEmbed.py
lazyllm/tools/rag/doc_node.py
lazyllm/tools/rag/rerank.py
tests/advanced_tests/standard_test/test_reranker.py

- Supported relevance score after reranker by addied it to instance of DocNode;
- https://github.com/LazyAGI/LazyLLM/issues/381
- 8 of https://github.com/LazyAGI/LazyLLM/issues/155
- Add online reranker of GLM.

Supported Relevance Score after Reranker, and Add Online Reranker of GLM.

---

examples/distill_deepseek_r1.py
lazyllm/components/deploy/vllm.py
lazyllm/module/module.py

Distill DeepSeek-R1

---

lazyllm/tools/rag/doc_node.py

Fixed a parameter misalignment issue in `ImageDocNode.__init__()` where the `content` parameter was missing when calling `super().__init__()`
- Added `None` as the `content` argument in `super().__init__()` to match `DocNode`'s parameter order:
```python
super().__init__(uid, group, embedding, parent, metadata, global_metadata=global_metadata, text=text)
super().__init__(uid, None, group, embedding, parent, metadata, global_metadata=global_metadata, text=text)

fix(ImageDocNode): Add missing `content` parameter in super().__init__()

---

lazyllm/components/deploy/__init__.py
lazyllm/components/deploy/mindie.py
lazyllm/components/deploy/mindie/config.json

支持1.0.rc3版本，请按照官方文档准备环境，建议在docker内启动
https://www.hiascend.com/document/detail/zh/mindie/10RC3/envdeployment/instg/mindie_instg_0026.html
简单模式支持通过指定模型名称启动服务，有复杂需求可以直接传入可用的config.json

support mind ie deployment

---

lazyllm/engine/engine.py

Modify the situation when using local models in the engine, if deploy is set to auto, the URL cannot be passed

Fix: Error in make_local_llm When deploy_method is Set to "auto"

---

lazyllm/components/embedding/embed.py

Modify the location where flagembedding is used

Fix: Reranker uses FlagEmbedding to report an error

---

lazyllm/module/llms/onlinemodule/base/onlineChatModuleBase.py

online chat module meets stream output bug when turns of the think mode.
```pyhton
import lazyllm
llm = lazyllm.OnlineChatModule(base_url="http://10.119.21.242:25121/v1/",
model='Qwen3-32B',
stream=True)
print(llm("hello, who are you", enable_thinking=False))
```
报错如下
```bash
RuntimeError: 
An error occured in <class 'lazyllm.module.llms.onlinemodule.supplier.openai.OpenAIModule'> with name None.
Args:
('hello, who are you',)
Kwargs
{}
Error messages:
list index out of range
Original traceback:
File "/home/LazyLLM/lazyllm/module/module.py", line 96, in __call__
r = self.forward(**args[0], **kw) if args and isinstance(args[0], kwargs) else self.forward(*args, **kw)
File "/home/LazyLLM/lazyllm/module/llms/onlinemodule/base/onlineChatModuleBase.py", line 196, in forward
extractor = …
```

[Bugfix]: Fix online chat module stream bug when turning off think mode
